server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
       defaultZone: http://eureka9000.com:9000/eureka,http://eureka9001.com:9001/eureka,http://eureka9002.com:9002/eureka
spring:
  application:
    name: feign-comsumer
  redis:
    database: 0
    host: 118.24.147.167
    port: 6379
    password:
    timeout: 60000





